### ISSUE TITLE
Link to Master App

### ISSUE THREAD

**Issue by Luis-Fernando-Molina** [AdvancedAlgos/ProjectWebsite#42]
Whrever appropiate, you should invite people to the system, not the telegram community.

https://app.advancedalgos.net

**Comment by julian-molina** [comment]
Done.

**Comment by Luis-Fernando-Molina** [comment]
Where is it. Show proof on image.

**Comment by Luis-Fernando-Molina** [comment]
![image](https://user-images.githubusercontent.com/9479367/47602506-4f3b7b00-d9e0-11e8-95b8-a3b210f4ccf9.png)

At this point there should be a menu that reads> Platform

Besides whatever other link that you could put inside the pages.

**Comment by julian-molina** [comment]
![image](https://user-images.githubusercontent.com/13994516/49077367-5fdb4d00-f23b-11e8-9a2f-bfb1525326e9.png)
